language: java

before_install:
- chmod +x gradlew

jdk:
- oraclejdk8

script: "./gradlew check"

deploy:
  edge: true
  provider: cloudfoundry
  username: seijiohara@cmu.edu
  password: $coobyDoo123
  api: https://api.run.pivotal.io
  organization: seijohara-cmu
  space: development
  on:
    repo: DanielSOhara27/Image-Gallery-Application
    branch: hw2

