language: java
before_install:
- chmod +x gradlew
jdk:
- oraclejdk8
script: "./gradlew check"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: seijiohara@cmu.edu
  password:
    secure: GgY+lq4ykuUh9m2h6fEDQUNnL62zsS4seLFiDrKlDGZbCZSy52qhUdyjM1OttFbJQi5d3P00xk0uvEC0N+yBMYJdrVNCWf5EwdkVu60vUla6GaUupitmDd97yPFcCVLHO2RO0RbYRcieKDK6o1elbf12d8FVYjEvSsMNpmEbgjZdRyYNUDN6/M8Z9Mta/5OiTHc70s70H7pvQdFpPt+6TMMBTYu8qur/HMy9mpZbStYNmjizrjQHrn8kPs74OrGiD9CQsrxzhaIYFuIOZqIb80/ya1HdOU8cUhxH9Mdg7tBZQvA7oI4BWtGXOF5ppKgRwE1Byb4Z0ft3e8PLagDNvbCU2yjIZDmqWXMip4iVqQKI59jiaSvte/Ig0woTsAe4DUB56uTnjV/TiLDwSOBivawNle7j0hKpWzfrL4afeB/sxsV/9iatXtW4esnG/nwutOPcGuaJXKMqR6Kl405a8yTGjLmt9rK+i+/0499fw1b0tMteWbvFmZuxPdpeMeL9d3pRfy4sggg9aL5cabydMD8yp/vsrEoOKe9K2bh0toRrqS5fSrnt4AiJVaUHpunRqz3MRWqhSWwD8jHXpZcWRKS2IJE5rRv+Vt3/vH8q4WSzlPmPRzPUn3iMGRRd2wlQMqxU4ONMGVU2ae8HQ89u8H4U4gWaVZZPFFK9zEiGyhA=
  organization: seijohara-cmu
  space: development
  on:
    repo: DanielSOhara27/Image-Gallery-Application
    branch: hw2
